config/routes.rb
Rails.application.routes.draw do

  mount Thredded::Engine => '/forum'

  # Set root to be the Thredded forums index page at /forum.
  root to: 'thredded/messageboards#index'

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  # Let /users/:id route to the profiles controller show action.
  # This is optional, but it allows you to have a link to a user's profile page.
  get '/users/:id' => 'profiles#show'
  get '/users' => 'profiles#index'

  post 'users/profiles/update_curp' => 'profiles#update_curp'
  post 'users/profiles/update_trajectory' => 'profiles#update_trajectory'

end

app/models/thredded/null_user.rb
# frozen_string_literal: true

module Thredded
  # A Thredded::NullUser stands in place of a real (mainapp supplied) User when:
  #
  # * user is not logged in (ie. the thredded_current_user)
  # * a user that was hard-deleted
  #   (e.g. if a post was made by a user, and then that user is destroyed, the post's user ID is nullified).
  class NullUser
    include ::Thredded::UserPermissions::Read::None
    include ::Thredded::UserPermissions::Write::None
    include ::Thredded::UserPermissions::Message::ReadersOfWriteableBoards
    include ::Thredded::UserPermissions::Moderate::None
    include ::Thredded::UserPermissions::Admin::None

    def thredded_private_topics
      Thredded::PrivateTopic.none
    end

    def id
      nil
    end

    def name
      I18n.t('thredded.null_user_name')
    end

    def to_s
      name
    end

    def valid?
      false
    end

    def thredded_anonymous?
      true
    end

    def thredded_user_detail
      Thredded::UserDetail.new
    end

    def thredded_user_preference
      Thredded::UserPreference.new
    end

    def thredded_display_name
      to_s
    end
  end
end

app/models/thredded/user_permissions/read/all.rb
# frozen_string_literal: true

module Thredded
  module UserPermissions
    module Read
      module All
        extend ActiveSupport::Concern
        included { extend ClassMethods }

        # @return [ActiveRecord::Relation<Thredded::Messageboard>] messageboards that the user can read
        def thredded_can_read_messageboards
          Thredded::Messageboard.all
        end

        # @param [Thredded::Messageboard] messageboard
        # @return [Boolean] Whether the user can read the given messageboard.
        def thredded_can_read_messageboard?(messageboard)
          scope = thredded_can_read_messageboards
          scope == Thredded::Messageboard.all || scope.include?(messageboard)
        end

        module ClassMethods
          # Users that can read some of the given messageboards.
          #
          # @param _messageboards [Array<Thredded::Messageboard>]
          # @return [ActiveRecord::Relation<Thredded.user_class>] users that can read the given messageboards
          def thredded_messageboards_readers(_messageboards)
            all
          end
        end
      end
    end
  end
end

app/models/thredded/user_permissions/read/none.rb
# frozen_string_literal: true

module Thredded
  module UserPermissions
    module Read
      module None
        extend ActiveSupport::Concern

        # @return [ActiveRecord::Relation<Thredded::Messageboard>] messageboards that the user can post in
        def thredded_can_read_messageboards
          Thredded::Messageboard.none
        end
      end
    end
  end
end

app/views/thredded/messageboards/_form.html.erb
<%= form_for messageboard, html: { class: 'thredded--form' } do |f| %>
    <ul class="thredded--form-list">
      <li>
        <%= f.label :name, t('thredded.messageboard.form.title_label') %>
        <%= f.text_field :name, required: true %>
        <%= render 'thredded/shared/field_errors', messages: f.object.errors[:name] %>
      </li>
      <li>
        <%= f.label :description, t('thredded.messageboard.form.description_label') %>
        <%= f.text_field :description %>
      </li>
      <li>
        <%- habilitar_secciones = false %>
        <% if habilitar_secciones%>
          <%= f.label :messageboard_group_id, t('thredded.messageboard.form.messageboard_group_id_label') %>
          <%= f.collection_select :messageboard_group_id, Thredded::MessageboardGroup.all, :id, :name,
                                  include_blank: t('thredded.messageboard.form.no_group') %>
        <%end %>
      </li>
      <li>
        <%= f.label :locked do %>
            <%= f.check_box :locked %> <%= t 'thredded.messageboard.form.locked_label' %>
        <% end %>
      </li>

      <li>
        <%= f.submit messageboard.persisted? ? t('thredded.messageboard.update') : t('thredded.messageboard.create'),
                     class: 'thredded--form--submit',
                     'data-disable-with' => messageboard.persisted? ?
                         t('thredded.messageboard.form.update_btn_submitting') :
                         t('thredded.messageboard.form.create_btn_submitting') %>
      </li>
    </ul>
<% end %>
<% if messageboard.persisted? and Thredded.show_messageboard_delete_button %>
  <%= button_to t('thredded.messageboard.form.delete'),
                messageboard_path(messageboard),
                method: 'delete',
                class: 'thredded--messageboard--delete',
                form_class: 'thredded--form',
                data: {confirm: t('thredded.messageboard.form.delete_confirm', messageboard_name: messageboard.name)}%>
<% end %>

app/views/thredded/messageboards/index.html.erb
<% content_for :thredded_page_title, t('thredded.messageboard.index.page_title') %>
<% content_for :thredded_page_id, 'thredded--messageboards-index' %>
<% content_for :thredded_breadcrumbs, render('thredded/shared/breadcrumbs') %>
<%= thredded_page do %>
  <%= define_svg_icons('thredded/follow.svg', 'thredded/lock.svg') %>
  <%= view_hooks.messageboards_index.container.render self, groups: @groups do %>
    <section class="thredded--main-section thredded--messageboards">
      <%= view_hooks.messageboards_index.list.render self, groups: @groups do %>

        <% if @groups.empty? %>
          <div class="thredded--flash-message thredded--flash-message--notice" data-thredded-flash-message="">
            Para tener acceso a los foros se requiere registrarse.
          </div>
        <% end %>

        <% @groups.each do |group| %>
          <% if group.name.present? %>
            <h3 class="thredded--messageboards-group--title">
              <%= link_to_if Thredded.show_messageboard_group_page,
                            group.name,
                            show_messageboard_group_path(group.id),
                            class: 'thredded--link' %>
            </h3>
          <% end %>
          <div class="thredded--messageboards-group">
            <%= view_hooks.messageboards_index.group.render self, group: group do %>
              <%= render partial: 'thredded/messageboards/messageboard',
                         collection: group.messageboards %>
            <% end %>
            <%= render partial: 'thredded/messageboards/grid_sizers' %>
          </div>
        <% end %>
      <% end %>

      <div class="thredded--messageboards--actions">
        <% if policy(Thredded::Messageboard.new).create? %>
          <a class="thredded--button" href="<%= new_messageboard_path %>" rel="nofollow">
            <%= t('thredded.messageboard.create') %>
          </a>
        <% end %>
        <%- habilitar_secciones = false %>
        <% if habilitar_secciones && policy(Thredded::MessageboardGroup.new).create? %>
          <a class="thredded--button" href="<%= new_messageboard_group_path %>" rel="nofollow">
            <%= t('thredded.messageboard_group.create') %>
          </a>
        <% end %>
      </div>
    </section>
  <% end %>
<% end %>