config/routes.rb
Rails.application.routes.draw do

  mount Thredded::Engine => '/forum'

  # Set root to be the Thredded forums index page at /forum.
  root to: 'thredded/messageboards#index'

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  # Let /users/:id route to the profiles controller show action.
  # This is optional, but it allows you to have a link to a user's profile page.
  get '/users/:id' => 'profiles#show'
  get '/users' => 'profiles#index'

  post 'users/profiles/update_curp' => 'profiles#update_curp'
  post 'users/profiles/update_trajectory' => 'profiles#update_trajectory'

end

app/models/thredded/null_user.rb
# frozen_string_literal: true

module Thredded
  # A Thredded::NullUser stands in place of a real (mainapp supplied) User when:
  #
  # * user is not logged in (ie. the thredded_current_user)
  # * a user that was hard-deleted
  #   (e.g. if a post was made by a user, and then that user is destroyed, the post's user ID is nullified).
  class NullUser
    include ::Thredded::UserPermissions::Read::None
    include ::Thredded::UserPermissions::Write::None
    include ::Thredded::UserPermissions::Message::ReadersOfWriteableBoards
    include ::Thredded::UserPermissions::Moderate::None
    include ::Thredded::UserPermissions::Admin::None

    def thredded_private_topics
      Thredded::PrivateTopic.none
    end

    def id
      nil
    end

    def name
      I18n.t('thredded.null_user_name')
    end

    def to_s
      name
    end

    def valid?
      false
    end

    def thredded_anonymous?
      true
    end

    def thredded_user_detail
      Thredded::UserDetail.new
    end

    def thredded_user_preference
      Thredded::UserPreference.new
    end

    def thredded_display_name
      to_s
    end
  end
end

app/models/thredded/user_permissions/read/all.rb
# frozen_string_literal: true

module Thredded
  module UserPermissions
    module Read
      module All
        extend ActiveSupport::Concern
        included { extend ClassMethods }

        # @return [ActiveRecord::Relation<Thredded::Messageboard>] messageboards that the user can read
        def thredded_can_read_messageboards
          Thredded::Messageboard.all
        end

        # @param [Thredded::Messageboard] messageboard
        # @return [Boolean] Whether the user can read the given messageboard.
        def thredded_can_read_messageboard?(messageboard)
          scope = thredded_can_read_messageboards
          scope == Thredded::Messageboard.all || scope.include?(messageboard)
        end

        module ClassMethods
          # Users that can read some of the given messageboards.
          #
          # @param _messageboards [Array<Thredded::Messageboard>]
          # @return [ActiveRecord::Relation<Thredded.user_class>] users that can read the given messageboards
          def thredded_messageboards_readers(_messageboards)
            all
          end
        end
      end
    end
  end
end

app/models/thredded/user_permissions/read/none.rb
# frozen_string_literal: true

module Thredded
  module UserPermissions
    module Read
      module None
        extend ActiveSupport::Concern

        # @return [ActiveRecord::Relation<Thredded::Messageboard>] messageboards that the user can post in
        def thredded_can_read_messageboards
          Thredded::Messageboard.none
        end
      end
    end
  end
end

app/views/thredded/shared/_breadcrumbs.html.erb
<ul class="thredded--navigation-breadcrumbs
  thredded--user-navigation--item thredded--user-navigation--private-topics">
  <li>
    <%#= link_to t('thredded.nav.all_messageboards'), messageboards_path %>
    <%= link_to messageboards_path do %>
      <%= inline_svg_tag 'thredded/home.svg',
                         class: 'thredded--icon--always reduce_svg',
                         title: t('thredded.nav.all_messageboards'), width: '16px', height: '16px' %>
      <span class="thredded--nav-text"><%= t('thredded.nav.all_messageboards') %></span>
    <% end %>
  </li>
  <% if messageboard_or_nil.try(:persisted?) %>
    <li><%= link_to messageboard.name, messageboard_topics_path(messageboard) %></li>
    <% if @topic %>
      <span><%= @topic.title %></span>
    <% end %>
  <% end %>
</ul>

app/views/thredded/shared/_cimav_header.html.erb
<div class="header-principal" style="flex: 1 1 auto; text-align: center; line-height: 20px; border: 0px red solid;">
  <figure style="margin: 0;">
    <!--
    <a href="https://cimav.edu.mx/" class="organization-shortname" rel="" >
      <img class="is-48x48" src="https://cimav.edu.mx/wp-content/themes/cimav2017/img/2logos.png" alt="" />
    </a>
    -->
    <span style="color: #003e90; font-size: x-large; padding-left: 15px; font-weight: 400; letter-spacing: 3px;" >
      Foro de Egresados
    </span>
  </figure>
</div>

app/views/thredded/shared/_nav.html.erb
<nav class="thredded--navigation">
  <ul class="thredded--user-navigation<%= ' thredded--user-navigation-standalone' if Thredded.standalone_layout? %>">
    <%= render 'thredded/shared/nav/moderation' %>
    <%= render 'thredded/shared/nav/notification_preferences', messageboard: messageboard_or_nil %>
    <%= render 'thredded/shared/nav/private_topics' if Thredded.private_messaging_enabled %>
    <% if Thredded.standalone_layout? %>
      <%= render 'thredded/shared/nav/standalone_users_list' if thredded_signed_in? %>
      <%= render 'thredded/shared/nav/standalone_profile' if thredded_signed_in? %>
      <%= render 'thredded/shared/nav/standalone' %> <%# es el desconectar %>
    <% end %>
  </ul>
  <% if content_for? :thredded_main_navigation %>
    <%= yield :thredded_main_navigation %>
  <% else %>
    <div class="thredded--main-navigation">
      <%# Navigation scoped to the current messageboard if any. %>
      <%= yield :thredded_breadcrumbs %>
      <%#= render 'thredded/search/form', messageboard: messageboard_or_nil %>
      <div class="thredded--spacer"></div>
      <ul class="thredded--scoped-navigation">
        <%= render 'thredded/shared/nav/unread_topics', messageboard: messageboard_or_nil %>
      </ul>
    </div>
  <% end %>
</nav>

app/views/thredded/shared/_page.html.erb
<%= content_tag(:div, id: 'thredded--container', class: thredded_container_classes, data: thredded_container_data) do %>
  <%= render 'thredded/shared/cimav_header' %>
  <%= render 'thredded/shared/header' %>
  <%= render 'thredded/shared/flash_messages' %>
  <%= yield :thredded_page_content %>
  <%= render 'thredded/shared/currently_online' if Thredded.currently_online_enabled %>
<%- end %>

<%# If thredded JS is loaded via an [async] script, the JS may
run before or after DOMContentLoaded. Expose a flag to Thredded
so it can initialize correctly. %>
<%= javascript_tag 'data-turbolinks-eval': 'false', nonce: true do %>
  document.addEventListener('DOMContentLoaded', function() {
    (window.Thredded = window.Thredded || {}).DOMContentLoadedFired = true;
  });
<% end %>